version: 2
jobs:
  test:
    docker:
      - image: verdigristech/ci-scala
    steps:
      - checkout
      - run:
          command: |
            sbt coverage test:test coverageReport
            bash <(curl -s https://codecov.io/bash)
      - persist_to_workspace:
          root: .
          paths:
            - target/
  deploy:
    docker:
      - image: verdigristech/ci-scala
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            sbt "+publish"
workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            # required since `deploy` has tag filters AND requires `test`
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
